### ISSUE TITLE
2進数便利！

### ISSUE THREAD

**Issue by C0B21133** [C0B21061/ProjExD#7]
https://github.com/C0B21061/ProjExD/blob/3c5ebf69fe0ac44e801a0c395a8926ad610bc268/ex02/calc.py#L95
2進数変換してくれるのはとてもいいなと思いました。
せっかく処理を関数にしているので
if __name__ == "__main__":
が使えるともっと良くなるのではと思いました

**Comment by C0B21061** [comment]
次回までに勉強しておきます。
コメントありがとうございます
